### ISSUE TITLE
Versa and RDF*, SPARQL* (RDFstar, SPARQLstar)?

### ISSUE THREAD

**Issue by westurner** [uogbuji/versa#28]
What are the similarities and differences and advantages and disadvantages of Versa and RDF* / SPARQL* (RDFstar / SPARQLstar) for Linked Data Property Graphs?

- https://w3c.github.io/rdf-star/
  - https://w3c.github.io/rdf-star/cg-spec/editors_draft.html
  - https://w3c.github.io/rdf-star/implementations.html

**Comment by uogbuji** [comment]
Hi @westurner. I'll keep this brief, because honestly it's a bit of a distraction for me to think of Versa in direct opposition to RDF and its ecosystem. The original idea for Versa was a query language for RDF, which was actually considered by the RDF query WG which eventually settled on SPARQL. I dislike using SPARQL a great deal, and I found the broader focus on ontologies, inference and the like to be counter to RDF's original spirit of simplicity.

I decided to expand Versa to cover my most common uses of linked data, adding a data model with the most important thing RDF is missing from my perspective: properties upon properties. This brings it somewhere in between RDF and property graphs. I continue to watch developments in PG, because that might be an area that gets it right enough for me to need Versa less, but for now, it fits the sweet spot for what I and my various company and personal projects are doing.

**Comment by westurner** [comment]
Thanks for the context.

- https://github.com/w3c/rdf-star/issues/7
- https://www.w3.org/2009/sparql/wiki/Feature:PropertyPaths
- https://www.w3.org/2014/data-shapes/wiki/SHACL-ShEx-Comparison

Without schema to validate the graph structure, how can property paths graph patterns remain flexible enough to match after online or offline schema migration? A general open issue only partly solved by modeling schema with the ORM?

**Comment by westurner** [comment]
No so useful for https://en.wikipedia.org/wiki/Spreading_activation , I suppose
